/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ciwmzxrbcjhakzllfffj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpd216eHJiY2poYWt6bGxmZmZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU1NzQ1ODIsImV4cCI6MjA4MTE1MDU4Mn0.fUVxQpQ-PnkCM4uBljpURSxhmqH_vJF1c_i5ZY0OhT4"

/**
 * 🚨 EMAIL CONFIRMATION ISSUE FIX 🚨
 * 
 * If you're seeing "Email not confirmed" error, follow these steps:
 * 
 * Option 1: Disable Email Confirmation (Recommended for Development)
 * -----------------------------------------------------------------
 * 1. Go to: https://supabase.com/dashboard/project/ciwmzxrbcjhakzllfffj
 * 2. Navigate to: Authentication → Providers
 * 3. Click on "Email" provider
 * 4. Toggle OFF "Confirm email"
 * 5. Click "Save"
 * 
 * Option 2: Use Email Confirmation (Production)
 * ----------------------------------------------
 * 1. Use a valid email address when signing up
 * 2. Check your inbox for confirmation email
 * 3. Click the confirmation link
 * 4. Return to the app and sign in
 * 
 * Option 3: Create Your Own Supabase Project
 * -------------------------------------------
 * 1. Go to: https://supabase.com
 * 2. Create a new project
 * 3. Go to Settings → API
 * 4. Copy your Project URL and anon public key
 * 5. Update the values above
 * 6. Disable email confirmation in Authentication settings
 * 7. Run the SQL migration from /supabase/migrations/001_create_tables.sql
 */